package com.ruoyi.marketing.domain;

/**
 * Created by 伊甸园商城 on 18/1/5.
 * 促销查询条件
 */
public enum MarketingItem {
    FALL_MARKETING, FULL_GIFT_MARKETING, PANIC_BUY_MARKETING, FULL_DOWN_MARKETING, FULL_DISCOUNT_MARKETING, FREE_SHIP_MARKETING, DEPOSIT_PRE_SALE_MARKETING, FULL_PRE_SALE_MARKETING, TRY_MARKETING, GROUP_MARKETING, CROWD_FUNDING_MARKETING
}
